// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sninfzshadsxbauagwkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuaW5menNoYWRzeGJhdWFnd2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTIyNTIsImV4cCI6MjA1OTgyODI1Mn0.Ja_U5Z5epk1ZZ4s_lKG-3Ye8OGGTyKhYvC73zjkXZwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);